### ISSUE TITLE
Investigate CI/CD tools and options

### ISSUE THREAD

**Issue by stoopidJSON** [CodeForBaltimore/ProjectTemplate#11]
### Task
We need a good idea of what our CI/CD pipeline will be with Heroku or otherwise. We need details about what tools could work for us, and what a solution should look like. 

### Acceptance Criteria
- [x] Document or ticket comments detailing options
- [x] Look into CircleCI with Heroku and Docker
- [x] Look into TravisCI with Heroku and Docker

**Comment by stoopidJSON** [comment]
After investigating our options I think the best thing for us to use is TravisCI and to emphasize unit testing in our code. This will allow us to perform validation before anything is merged into `master`.
