### ISSUE TITLE
Split Golang Project

### ISSUE THREAD

**Issue by stoopidJSON** [CodeForBaltimore/ProjectTemplate#14]
### Task
We need to fork this repo and setup the Golang-specific variant.

### Acceptance Criteria
- [ ] ProjectTemplate-Golang repo created
- [ ] `/golang/Readme.md` contents merged into top-level `README` in new repo
- [ ] all contents of `/golang` moved to top-level of new repo and project structure adheres to Golang best practices
- [ ] `/golang` removed from this repo
- [ ] PR's merged to `master` for both repo's. 

### Notes
Even though this will take place across two repo's, we'll track progress here.
