### ISSUE TITLE
Split Java Project

### ISSUE THREAD

**Issue by stoopidJSON** [CodeForBaltimore/ProjectTemplate#15]
### Task
We need to fork this repo and setup the Golang-specific variant.

### Acceptance Criteria
- [ ] ProjectTemplate-Java repo created
- [ ] `/java/Readme.md` contents merged into top-level `README` in new repo
- [ ] all contents of `/java` moved to top-level of new repo and project structure adheres to Java best practices (use of `/src`)
- [ ] `/java` removed from this repo
- [ ] PR's merged to `master` for both repo's. 

### Notes
Even though this will take place across two repo's, we'll track progress here.
