### ISSUE TITLE
Split Python project

### ISSUE THREAD

**Issue by stoopidJSON** [CodeForBaltimore/ProjectTemplate#16]
### Task
We need to fork this repo and setup the Python-specific variant.

### Acceptance Criteria
- [x] ProjectTemplate-Python repo created
- [x] `/python/README.md` contents merged into top-level `README` in new repo
- [x] all contents of `/python` moved to top-level of new repo and project structure adheres to Python best practices
- [x] `/python` removed from this repo
- [x] PR's merged to `master` for both repo's. 

### Notes
Even though this will take place across two repo's, we'll track progress here.
