### ISSUE TITLE
Split Shiny Project 

### ISSUE THREAD

**Issue by stoopidJSON** [CodeForBaltimore/ProjectTemplate#17]
### Task
We need to fork this repo and setup the Shiny-specific variant.

### Acceptance Criteria
- [x] ProjectTemplate-Shiny repo created
- [ ] `/shiny/Readme.md` contents merged into top-level `README` in new repo
- [ ] all contents of `/shiny` moved to top-level of new repo and project structure adheres to Shiny/R best practices
- [ ] `/shiney` removed from this repo
- [ ] PR's merged to `master` for both repo's. 

### Notes
Even though this will take place across two repo's, we'll track progress here.

## Depends on 
#6
